import{a as d,i as h,S as L}from"./assets/vendor-b42c18af.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const y=document.querySelector(".container ul"),i=document.querySelector(".loader"),m=document.querySelector(".form"),w=document.querySelector("input"),r=document.createElement("button");r.textContent="Load more";r.style.margin="0 auto";r.style.marginTop="15px";r.style.width="150px";i.after(r);r.style.display="none";let l="",c=1;const p=15,g={key:"42291336-b4c9ef387c9d7e209159058e7",image_type:"photo",orientation:"horizontal",safesearch:!0};d.defaults.baseURL="https://pixabay.com/api/";const P=async()=>{try{return(await d.get("?",{params:{q:l,...g,page:1,per_page:p}})).data.totalHits}catch(a){return console.log(a),0}},v=P();let f=Math.ceil(v/p);m.addEventListener("submit",async a=>{if(a.preventDefault(),c=1,y.innerHTML="",l=w.value.trim(),!l)h.error({title:"Error",message:"Please enter a search term",position:"topRight"});else{i.style.display="block",r.style.display="none";try{const e=await d.get("?",{params:{q:l,...g,page:c,per_page:p}});!e.data.hits||e.data.hits.length===0?h.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",icon:""}):(b(e.data.hits),r.style.display="block"),i.style.display="none"}catch(e){i.style.display="none",r.style.display="none",console.log(e)}}m.reset()});const b=a=>{a.forEach(s=>{const n=`<li class="photo">
            <a href="${s.largeImageURL}" data-lightbox="photos">
                <img src="${s.webformatURL}" alt="${s.tags}" title="${s.tags}" class="img">
            </a>
            <ul class="list">
                <li class="item"><h2>Likes <span>${s.likes}</span></h2></li>
                <li class="item"><h2>Views <span>${s.views}</span></h2></li>
                <li class="item"><h2>Comments <span>${s.comments}</span></h2></li>
                <li class="item"><h2>Downloads <span>${s.downloads}</span></h2></li>
            </ul>
        </li>`;y.insertAdjacentHTML("beforeend",n)}),new L(".photos a",{}).refresh()};r.addEventListener("click",async a=>{i.style.display="block";try{c++;const e=await d.get("?",{params:{q:l,...g,page:c,per_page:p}});i.style.display="none",b(e.data.hits);const s=y.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:s*3,behavior:"smooth"});const n=e.data.totalHits;f=Math.ceil(n/p),c>=f&&(r.style.display="none",h.error({position:"topRight",message:"We're sorry, but you've reached the end of search results."}))}catch(e){i.style.display="none",console.log(e)}});
//# sourceMappingURL=commonHelpers.js.map
