import{a as h,i as u,S as b}from"./assets/vendor-b42c18af.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const p=document.querySelector(".container ul"),a=document.querySelector(".loader"),m=document.querySelector(".form"),L=document.querySelector("input"),r=document.createElement("button");r.textContent="Load more";r.style.margin="0 auto";r.style.marginTop="15px";r.style.width="150px";p.after(r);r.style.display="none";let l="",c=1;const y=15,w=Math.ceil(100/y),g={key:"42291336-b4c9ef387c9d7e209159058e7",image_type:"photo",orientation:"horizontal",safesearch:!0};h.defaults.baseURL="https://pixabay.com/api/";m.addEventListener("submit",async i=>{if(i.preventDefault(),p.innerHTML="",l=L.value.trim(),!l)u.error({title:"Error",message:"Please enter a search term",position:"topRight"});else{a.style.display="block",r.style.display="none";try{const t=await h.get("?",{params:{q:l,...g,page:c,per_page:y}});!t.data.hits||t.data.hits.length===0?u.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",icon:""}):(f(t.data.hits),r.style.display="block"),a.style.display="none"}catch(t){a.style.display="none",r.style.display="none",console.log(t)}}m.reset()});const f=i=>{i.forEach(s=>{const n=`<li class="photo">
            <a href="${s.largeImageURL}" data-lightbox="photos">
                <img src="${s.webformatURL}" alt="${s.tags}" title="${s.tags}" class="img">
            </a>
            <ul class="list">
                <li class="item"><h2>Likes <span>${s.likes}</span></h2></li>
                <li class="item"><h2>Views <span>${s.views}</span></h2></li>
                <li class="item"><h2>Comments <span>${s.comments}</span></h2></li>
                <li class="item"><h2>Downloads <span>${s.downloads}</span></h2></li>
            </ul>
        </li>`;p.insertAdjacentHTML("beforeend",n)}),new b(".photos a",{}).refresh()};r.addEventListener("click",async i=>{if(a.style.display="block",c>w)return a.style.display="none",r.style.display="none",u.error({position:"topRight",message:"We're sorry, there are no more posts to load"});try{c++;const t=await h.get("?",{params:{q:l,...g,page:c,per_page:y}});a.style.display="none",f(t.data.hits);const s=p.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:s*3.45,behavior:"smooth"})}catch(t){a.style.display="none",console.log(t)}});
//# sourceMappingURL=commonHelpers.js.map
